/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret cadratin",iexcl:"Point d'exclamation inversГ©",cent:"Symbole Cent",pound:"Symbole Livre Sterling",curren:"Symbole monГ©taire",yen:"Symbole Yen",brvbar:"Barre verticale scindГ©e",sect:"Section",uml:"TrГ©ma",copy:"Symbole Copyright",ordf:"Indicateur ordinal fГ©minin",laquo:"Guillemet franГ§ais ouvrant",
not:"Crochet de nГ©gation",reg:"Marque dГ©posГ©e",macr:"Macron",deg:"DegrГ©",sup2:"Exposant 2",sup3:"\\tExposant 3",acute:"Accent aigu",micro:"Omicron",para:"Paragraphe",middot:"Point mГ©dian",cedil:"CГ©dille",sup1:"\\tExposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franГ§ais fermant",frac14:"Un quart",frac12:"Un demi",frac34:"Trois quarts",iquest:"Point d'interrogation inversГ©",Agrave:"A majuscule accent grave",Aacute:"A majuscule accent aigu",Acirc:"A majuscule accent circonflexe",Atilde:"A majuscule avec caron",
Auml:"A majuscule trГ©ma",Aring:"A majuscule avec un rond au-dessus",AElig:"Г† majuscule ligaturГ©s",Ccedil:"C majuscule cГ©dille",Egrave:"E majuscule accent grave",Eacute:"E majuscule accent aigu",Ecirc:"E majuscule accent circonflexe",Euml:"E majuscule trГ©ma",Igrave:"I majuscule accent grave",Iacute:"I majuscule accent aigu",Icirc:"I majuscule accent circonflexe",Iuml:"I majuscule trГ©ma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N majuscule avec caron",Ograve:"O majuscule accent grave",Oacute:"O majuscule accent aigu",
Ocirc:"O majuscule accent circonflexe",Otilde:"O majuscule avec caron",Ouml:"O majuscule trГ©ma",times:"Multiplication",Oslash:"O majuscule barrГ©",Ugrave:"U majuscule accent grave",Uacute:"U majuscule accent aigu",Ucirc:"U majuscule accent circonflexe",Uuml:"U majuscule trГ©ma",Yacute:"Y majuscule accent aigu",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a minuscule accent grave",aacute:"a minuscule accent aigu",acirc:"a minuscule accent circonflexe",atilde:"a minuscule avec caron",
auml:"a minuscule trГ©ma",aring:"a minuscule avec un rond au-dessus",aelig:"Г¦ minuscule ligaturГ©s",ccedil:"c minuscule cГ©dille",egrave:"e minuscule accent grave",eacute:"e minuscule accent aigu",ecirc:"e minuscule accent circonflexe",euml:"e minuscule trГ©ma",igrave:"i minuscule accent grave",iacute:"i minuscule accent aigu",icirc:"i minuscule accent circonflexe",iuml:"i minuscule trГ©ma",eth:"Lettre minuscule islandaise ED",ntilde:"n minuscule avec caron",ograve:"o minuscule accent grave",oacute:"o minuscule accent aigu",
ocirc:"o minuscule accent circonflexe",otilde:"o minuscule avec caron",ouml:"o minuscule trГ©ma",divide:"Division",oslash:"o minuscule barrГ©",ugrave:"u minuscule accent grave",uacute:"u minuscule accent aigu",ucirc:"u minuscule accent circonflexe",uuml:"u minuscule trГ©ma",yacute:"y minuscule accent aigu",thorn:"Lettre islandaise thorn minuscule",yuml:"y minuscule trГ©ma",OElig:"ligature majuscule latine Е’",oelig:"ligature minuscule latine Е“",372:"W majuscule accent circonflexe",374:"Y majuscule accent circonflexe",
373:"w minuscule accent circonflexe",375:"y minuscule accent circonflexe",sbquo:"Guillemet simple fermant (anglais)",8219:"Guillemet-virgule supГ©rieur culbutГ©",bdquo:"Guillemet-virgule double infГ©rieur",hellip:"Points de suspension",trade:"Marque commerciale (trade mark)",9658:"FlГЁche noire pointant vers la droite",bull:"Gros point mГ©dian",rarr:"FlГЁche vers la droite",rArr:"Double flГЁche vers la droite",hArr:"Double flГЁche vers la gauche",diams:"Carreau noir",asymp:"Presque Г©gal"});