/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","zh",{euro:"ж­ђе…ѓз¬¦и™џ",lsquo:"е·¦е–®еј•и™џ",rsquo:"еЏіе–®еј•и™џ",ldquo:"е·¦й›™еј•и™џ",rdquo:"еЏій›™еј•и™џ",ndash:"зџ­з ґжЉи™џ",mdash:"й•·з ґжЉи™џ",iexcl:"еЂ’зЅ®зљ„й©ље†и™џ",cent:"зѕЋе€†з¬¦и™џ",pound:"и‹±йЋЉз¬¦и™џ",curren:"иІЁе№Јз¬¦и™џ",yen:"ж—Ґењ“з¬¦и™џ",brvbar:"Broken bar",sect:"з« зЇЂз¬¦и™џ",uml:"е€†йџіз¬¦и™џ",copy:"з‰€ж¬Љз¬¦и™џ",ordf:"й›ЊжЂ§з¬¦и™џ",laquo:"е·¦й›™и§’ж‹¬и™џ",not:"Not з¬¦и™џ",reg:"иЁ»е†Ље•†жЁ™з¬¦и™џ",macr:"й•·йџіз¬¦и™џ",deg:"еє¦ж•ёз¬¦и™џ",sup2:"дёЉжЁ™е­— 2",sup3:"дёЉжЁ™е­— 3",acute:"е°–йџіз¬¦и™џ",micro:"Micro sign",para:"ж®µиђЅз¬¦и™џ",middot:"дё­й–“й»ћ",cedil:"е­—жЇЌ C дё‹йќўзљ„е°ѕећ‹з¬¦и™џ ",sup1:"дёЉжЁ™",ordm:"й›„жЂ§з¬¦и™џ",raquo:"еЏій›™и§’ж‹¬и™џ",frac14:"е››е€†д№‹дёЂз¬¦и™џ",frac12:"Vulgar fraction one half",
frac34:"Vulgar fraction three quarters",iquest:"Inverted question mark",Agrave:"Latin capital letter A with grave accent",Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",Auml:"ж‹‰дёЃе¤§еЇ«е­—жЇЌ E её¶е€†йџіз¬¦и™џ",Aring:"ж‹‰дёЃе¤§еЇ«е­—жЇЌ A её¶дёЉењ“ењ€",AElig:"ж‹‰дёЃе¤§еЇ«е­—жЇЌ Г†",Ccedil:"ж‹‰дёЃе¤§еЇ«е­—жЇЌ C её¶дё‹е°ѕз¬¦и™џ",Egrave:"Latin capital letter E with grave accent",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",
Igrave:"Latin capital letter I with grave accent",Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",ETH:"Latin capital letter Eth",Ntilde:"Latin capital letter N with tilde",Ograve:"Latin capital letter O with grave accent",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",
times:"д№и™џ",Oslash:"ж‹‰дёЃе¤§еЇ«е­—жЇЌ O её¶зІ—з·љз¬¦и™џ",Ugrave:"Latin capital letter U with grave accent",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",Yacute:"Latin capital letter Y with acute accent",THORN:"Latin capital letter Thorn",szlig:"Latin small letter sharp s",agrave:"Latin small letter a with grave accent",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",
auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"Latin small letter Г¦",ccedil:"Latin small letter c with cedilla",egrave:"Latin small letter e with grave accent",eacute:"Latin small letter e with acute accent",ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"Latin small letter i with grave accent",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",
eth:"Latin small letter eth",ntilde:"Latin small letter n with tilde",ograve:"Latin small letter o with grave accent",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",divide:"Division sign",oslash:"Latin small letter o with stroke",ugrave:"Latin small letter u with grave accent",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",
uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"Latin small letter thorn",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",
hellip:"Horizontal ellipsis",trade:"Trade mark sign",9658:"Black right-pointing pointer",bull:"Bullet",rarr:"Rightwards arrow",rArr:"Rightwards double arrow",hArr:"Left right double arrow",diams:"Black diamond suit",asymp:"Almost equal to"});