/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilitГ©",contents:"Contenu de l'aide. Pour fermer ce dialogue, appuyez sur la touche Ech (Echappement).",legend:[{name:"GГ©nГ©ral",items:[{name:"Barre d'outils de l'Г©diteur",legend:"Appuyer sur ${toolbarFocus} pour accГ©der Г  la barre d'outils. Se dГ©placer vers les groupes suivant ou prГ©cГ©dent de la barre d'outil avec les touches TAB et SHIFT-TAB. Se dГ©placer vers les boutons suivant ou prГ©cГ©dent de la barre d'outils avec les touches FLECHE DROITE et FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour activer le bouton de barre d'outils."},
{name:"Dialogue de l'Г©diteur",legend:"A l'intГ©rieur d'un dialogue, appuyer sur la touche TAB pour naviguer jusqu'au champ de dalogue suivant, appuyez sur les touches SHIFT + TAB pour revenir au champ prГ©cГ©dent, appuyez sur la touche ENTRER pour soumettre le dialogue, appuyer sur la touche ESC pour annuler le dialogue. Pour les dialogues avec plusieurs pages d'onglets, appuyer sur ALT + F10 pour naviguer jusqu'Г  la liste des onglets. Puis se dГ©placer vers l'onglet suivant avec la touche TAB ou FLECHE DROITE. Se dГ©placer vers l'onglet prГ©cГ©dent avec les touches SHIFT + TAB ou FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour sГ©lectionner la page de l'onglet."},
{name:"Menu contextuel de l'Г©diteur",legend:"Appuyer sur ${contextMenu} ou entrer le RACCOURCI CLAVIER pour ouvrir le menu contextuel. Puis se dГ©placer vers l'option suivante du menu avec les touches TAB ou FLECHE BAS. Se dГ©placer vers l'option prГ©cГ©dente avec les touches  SHIFT+TAB ou FLECHE HAUT. appuyer sur la BARRE D'ESPACE ou la touche ENTREE pour sГ©lectionner l'option du menu. Oovrir le sous-menu de l'option courante avec la BARRE D'ESPACE ou les touches ENTREE ou FLECHE DROITE. Revenir Г  l'Г©lГ©ment de menu parent avec les touches Ech ou FLECHE GAUCHE. Fermer le menu contextuel avec Ech."},
{name:"Zone de liste de l'Г©diteur",legend:"Dans la liste en menu dГ©roulant, se dГ©placer vers l'Г©lГ©ment suivant de la liste avec les touches TAB ou FLECHE BAS. Se dГ©placer vers l'Г©lГ©ment prГ©cГ©dent de la liste avec les touches MAJ + TAB ou FLECHE HAUT. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour sГ©lectionner l'option dans la liste. Appuyer sur ESC pour fermer le menu dГ©roulant."},{name:"Barre d'emplacement des Г©lГ©ments de l'Г©diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre d'emplacement des Г©lГ©ments de l'Г©diteur. Se dГ©placer vers le bouton d'Г©lГ©ment suivant avec les touches TAB ou FLECHE DROITE. Se dГ©placer vers le bouton d'Г©lГ©ment prГ©cГ©dent avec les touches MAJ+TAB ou FLECHE GAUCHE. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour sГ©lectionner l'Г©lГ©ment dans l'Г©diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Refaire la commande",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulignГ©",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"AccГ©der Г  la prГ©cГ©dente commande d'espace de mise au point",
legend:"Appuyez sur ${accessPreviousSpace} pour accГ©der Г  l'espace hors d'atteinte le plus proche avant le caret, par exemple: deux Г©lГ©ments HR adjacents. RГ©pГ©tez la combinaison de touches pour atteindre les espaces de mise au point distants."},{name:"AccГЁs Г  la prochaine commande de l'espace de mise au point",legend:"Appuyez sur ${accessNextSpace} pour accГ©der au plus proche espace de mise au point hors d'atteinte aprГЁs le caret, par exemple: deux Г©lГ©ments HR adjacents. rГ©pГ©tez la combinaison de touches pour atteindre les espace de mise au point distants."},
{name:" Aide AccessibilitГ©",legend:"Appuyer sur ${a11yHelp}"}]}],backspace:"Retour arriГЁre",tab:"Tabulation",enter:"EntrГ©e",shift:"Majuscule",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Verr. Maj.",escape:"Echap",pageUp:"Page supГ©rieure",pageDown:"Page infГ©rieure",end:"Fin",home:"Retour",leftArrow:"FlГЁche gauche",upArrow:"FlГЁche haute",rightArrow:"FlГЁche droite",downArrow:"FlГЁche basse",insert:"Insertion","delete":"Supprimer",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",
selectKey:"Touche menu",numpad0:"PavГ© numГ©rique 0",numpad1:"PavГ© numГ©rique 1",numpad2:"PavГ© numГ©rique 2",numpad3:"PavГ© numГ©rique 3",numpad4:"PavГ© numГ©rique 4",numpad5:"PavГ© numГ©rique 5",numpad6:"PavГ© numГ©rique 6",numpad7:"PavГ© numГ©rique 7",numpad8:"PavГ© numГ©rique 8",numpad9:"PavГ© numГ©rique 9",multiply:"Multiplier",add:"Addition",subtract:"Soustraire",decimalPoint:"Point dГ©cimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",
numLock:"Verrouillage numГ©rique",scrollLock:"ArrГЄt dГ©filement",semiColon:"Point virgule",equalSign:"Signe Г©gal",comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"ParenthГЁse ouvrante",backSlash:"Barre oblique inverse",closeBracket:"ParenthГЁse fermante",singleQuote:"Apostrophe"});