/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotyczД…ce dostД™pnoЕ›ci",contents:"ZawartoЕ›Д‡ pomocy. WciЕ›nij ESC, aby zamknД…Д‡ to okno.",legend:[{name:"Informacje ogГіlne",items:[{name:"Pasek narzД™dzi edytora",legend:"WciЕ›nij ${toolbarFocus} aby przejЕ›Д‡ do paska narzД™dzi. PrzejdЕє do nastД™pnej i poprzedniej grupy narzД™dzi uЕјywajД…c TAB oraz SHIFT-TAB. PrzejdЕє do nastД™pnego i poprzedniego narzД™dzia uЕјywajД…c STRZAЕЃKI W PRAWO lub STRZAЕЃKI W LEWO. WciЕ›nij SPACJД lub ENTER, aby aktywowaД‡ zaznaczone narzД™dzie."},
{name:"Okno dialogowe edytora",legend:"BД™dД…c w oknie dialogowym wciЕ›nij TAB aby przejЕ›Д‡ do nastД™pnego pola dialogowego, wciЕ›nij SHIFT + TAB aby przejЕ›Д‡ do poprzedniego pola, wciЕ›nij ENTER aby wysЕ‚aД‡ dialog, wciЕ›nij ESC aby anulowaД‡ dialog. Dla okien dialogowych z wieloma zakЕ‚adkami, wciЕ›nij ALT + F10 aby przejЕ›Д‡ do listy zakЕ‚adek. Gdy to zrobisz przejdЕє do nastД™pnej zakЕ‚adki wciskajД…c TAB lub STRZAЕЃKД W PRAWO. PrzejdЕє do poprzedniej zakЕ‚adki wciskajД…c SHIFT + TAB lub STRZAЕЃKД W LEWO. WciЕ›nij SPACJД lub ENTER aby wybraД‡ zakЕ‚adkД™."},
{name:"Menu kontekstowe edytora",legend:"WciЕ›nij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzyД‡ menu kontekstowe. PrzejdЕє do nastД™pnej pozycji menu wciskajД…c TAB lub STRZAЕЃKД W DГ“ЕЃ. PrzejdЕє do poprzedniej pozycji menu wciskajД…c SHIFT + TAB lub STRZAЕЃKД W GГ“RД. WciЕ›nij SPACJД lub ENTER aby wygraД‡ pozycjД™ menu. OtwГіrz pod-menu obecnej pozycji wciskajД…c SPACJД lub ENTER lub STRZAЕЃKД W PRAWO. WrГіД‡ do pozycji nadrzД™dnego menu wciskajД…c ESC lub STRZAЕЃKД W LEWO. Zamknij menu wciskajД…c ESC."},{name:"Lista w edytorze",
legend:"W polu listy moЕјesz przechodziД‡ do nastД™pnego elementu za pomocД… klawisza TAB lub STRZAЕЃKI W DГ“ЕЃ. Poprzedni element osiД…gniesz za pomocД… SHIFT+TAB lub STRZAЕЃKI W GГ“RД. Za pomocД… SPACJI lub ENTERA wybierzesz danД… opcjД™ z listy, a za pomocД… klawisza ESC opuЕ›cisz listД™."},{name:"Pasek Е›cieЕјki elementГіw edytora",legend:"NaciЕ›nij ${elementsPathFocus} w celu przejЕ›cia do paska Е›cieЕјki elementГіw edytora. W celu przejЕ›cia do kolejnego elementu naciЕ›nij klawisz Tab lub StrzaЕ‚ki w prawo. W celu przejЕ›cia do poprzedniego elementu naciЕ›nij klawisze Shift+Tab lub StrzaЕ‚ki w lewo. By wybraД‡ element w edytorze, uЕјyj klawisza Spacji lub Enter."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"NaciЕ›nij ${undo}"},{name:"Polecenie PonГіw",legend:"NaciЕ›nij ${redo}"},{name:"Polecenie Pogrubienie",legend:"NaciЕ›nij ${bold}"},{name:"Polecenie Kursywa",legend:"NaciЕ›nij ${italic}"},{name:"Polecenie PodkreЕ›lenie",legend:"NaciЕ›nij ${underline}"},{name:"Polecenie Wstaw/ edytuj odnoЕ›nik",legend:"NaciЕ›nij ${link}"},{name:"Polecenie schowaj pasek narzД™dzi",legend:"NaciЕ›nij ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Pomoc dotyczД…ca dostД™pnoЕ›ci",legend:"NaciЕ›nij ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"StrzaЕ‚ka w lewo",
upArrow:"StrzaЕ‚ka w gГіrД™",rightArrow:"StrzaЕ‚ka w prawo",downArrow:"StrzaЕ‚ka w dГіЕ‚",insert:"Insert","delete":"Delete",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",
numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"PrzemnГіЕј",add:"Plus",subtract:"Minus",decimalPoint:"Separator dziesiД™tny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ељrednik",equalSign:"Znak rГіwnoЕ›ci",comma:"Przecinek",dash:"Pauza",
period:"Kropka",forwardSlash:"UkoЕ›nik prawy",graveAccent:"Akcent sЕ‚aby",openBracket:"Nawias kwadratowy otwierajД…cy",backSlash:"UkoЕ›nik lewy",closeBracket:"Nawias kwadratowy zamykajД…cy",singleQuote:"Apostrof"});