/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt",{title:"InstruГ§Гµes de Acessibilidade",contents:"ConteГєdos da Ajuda. Pressione em 'ESC' para fechar esta janela.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Clique em ${toolbarFocus} para navegar para a barra de ferramentas. VГЎ para o grupo da barra de ferramentas anterior e seguinte com TAB e SHIFT+TAB. VГЎ para o botГЈo da barra de ferramentas anterior com a SETA DIREITA ou ESQUERDA. Pressione ESPAГ‡O ou ENTER para ativar o botГЈo da barra de ferramentas."},
{name:"Janela do Editor",legend:"Dentro de uma janela, pressione TAB para navigar para o campo da janela seguinte, pressione SHIFT + TAB para mover para o campo anterior, pressione ENTER para submeter a janela, pressione ESC para cancelar a janela. Para as janelas que tГЄm mГєltiplos pГЎginas com separadores, pressione ALT + F10 para navegar para a lista do separador. Depois mova para o seguinte separador com TAB ou SETA DIREITA. Mover para o separador anterior com SHIFT + TAB ou SETA ESQUERDA. Pressione ESPAГ‡O ou ENTER para selecionar o separador da pГЎgina."},
{name:"Menu de Contexto do Editor",legend:"Clique em ${contextMenu} ou TECLA APLICAГ‡ГѓO para abrir o menu de contexto. Depois vГЎ para a opГ§ГЈo do menu seguinte com TAB ou SETA PARA BAIXO. VГЎ para a opГ§ГЈo anterior com  SHIFT+TAB ou SETA PARA CIMA. Pressione ESPAГ‡O ou ENTER para selecionar a opГ§ГЈo do menu.  Abra o submenu da opГ§ГЈo atual com ESPAГ‡O, ENTER ou SETA DIREITA. GVГЎ para o item do menu parente  com ESC ou SETA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa Lista Editor",legend:"Dentro da caixa da lista, vГЎ para o itemda lista seguinte com TAB ou SETA PARA BAIXO. Move VГЎ parao item da lista anterior com SHIFT+TAB ou SETA PARA BAIXO. Pressione ESPAГ‡O ou ENTER para selecionar a opГ§ГЈo da lista. Pressione ESC para fechar a caisa da lista."},
{name:"Caminho Barra Elemento Editor",legend:"Clique em ${elementsPathFocus} para navegar para a barra do caminho dos elementos. VГЎ para o botГЈo do elemento seguinte com TAB ou SETA DIREITA. VГЎ para o botГЈo anterior com   SHIFT+TAB ou SETA ESQUERDA. Pressione ESPAГ‡O ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:"Comando de Anular",legend:"Pressione ${undo}"},{name:"Comando de Refazer",legend:"Pressione ${redo}"},{name:"Comando de Negrito",legend:"Pressione ${bold}"},
{name:"Comando de ItГЎlico",legend:"Pressione ${italic}"},{name:"Comando de Sublinhado",legend:"Pressione ${underline}"},{name:"Comando de HiperligaГ§ГЈo",legend:"Pressione ${link}"},{name:"Comando de Ocultar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acesso comando do espaГ§o focus anterior",legend:"Clique em ${accessPreviousSpace} para aceder ao espaГ§o do focos inalcanГ§ГЎvel mais perto antes do sinal de omissГЈo, por exemplo: dois elementos HR adjacentes. Repetir a combinaГ§ГЈo da chave para alcanГ§ar os espaГ§os dos focos distantes."},
{name:"Acesso comando do espaГ§o focus seguinte",legend:"Pressione ${accessNextSpace} para aceder ao espaГ§o do focos inalcanГ§ГЎvel mais perto depois do sinal de omissГЈo, por exemplo: dois elementos HR adjacentes. Repetir a combinaГ§ГЈo da chave para alcanГ§ar os espaГ§os dos focos distantes."},{name:"Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",
pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});